name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest" # or: "latest"

jobs:
  packer:
    runs-on: macos-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `make release`
        id: release
        run: "make release"
